import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/common/Navbar'
import Home from '../components/common/Home'

interface HomePageProps {}

const index: NextPage<HomePageProps> = () => {
  return (
    <div>
      <Head>
        <title>CineStock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home />

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default index
