import { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import Navbar from '../components/common/Navbar'
import Home from '../components/common/Home'
import { IMovie } from '../types/movie'
import { IWatchList } from '../types/watchList'

const index: NextPage<Props> = (props) => {
  return (
    <div>
      <Head>
        <title>CineStock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home movies={props.movies} watchList={props.watchList} />

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const dummyMoviesUrl = `${process.env.API_URL}/movies/landing`
  const dummyMoviesRes = await axios.get<IMovie[]>(dummyMoviesUrl)

  const dummyWatchListUrl = `${process.env.API_URL}/watch-list/landing`
  const dummyWatchListRes = await axios.get<IWatchList[]>(dummyWatchListUrl)
  return {
    props: { movies: dummyMoviesRes.data, watchList: dummyWatchListRes.data },
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default index
